# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gossip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gossip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgossip.proto\x12\x06gossip\"I\n\rWeightMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x15\n\rmodel_weights\x18\x02 \x01(\x0c\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x02\":\n\rExchangeReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10\x61veraged_weights\x18\x02 \x01(\x0c\x32M\n\nGossipNode\x12?\n\x0f\x45xchangeWeights\x12\x15.gossip.WeightMessage\x1a\x15.gossip.ExchangeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEIGHTMESSAGE']._serialized_start=24
  _globals['_WEIGHTMESSAGE']._serialized_end=97
  _globals['_EXCHANGEREPLY']._serialized_start=99
  _globals['_EXCHANGEREPLY']._serialized_end=157
  _globals['_GOSSIPNODE']._serialized_start=159
  _globals['_GOSSIPNODE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
